name: Flutter e Java Version Check

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Verificar Versão do Flutter
        run: flutter --version

      - name: Verificar Versão do Java
        run: java -version
