name: Flutter and Dart Version Check

on:
  push:
    branches:
      - main

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Flutter version
        run: |
          echo "Checking Flutter version..."
          flutter --version

      - name: Check Dart version
        run: |
          echo "Checking Dart version..."
          dart --version

      - name: Validate Flutter version
        run: |
          required_flutter_version=$(yq e '.environment.flutter' pubspec.yaml | tr -d '>=<')
          current_flutter_version=$(flutter --version --machine | yq e '.flutterVersion' -)
          if ! [[ "$current_flutter_version" =~ ^$required_flutter_version ]]; then
            echo "Flutter version mismatch: Required $required_flutter_version but found $current_flutter_version"
            exit 1
          fi

      - name: Validate Dart version
        run: |
          required_dart_version=$(yq e '.environment.sdk' pubspec.yaml | tr -d '>=<')
          current_dart_version=$(dart --version --machine | yq e '.dartVersion' -)
          if ! [[ "$current_dart_version" =~ ^$required_dart_version ]]; then
            echo "Dart version mismatch: Required $required_dart_version but found $current_dart_version"
            exit 1
          fi
