#!/bin/bash

# Create .env file with placeholder values
echo "REBCA_FLUTTER_GITHUB_TOKEN=YOUR_GITHUB_TOKEN" > .env
echo "REBCA_FLUTTER_CLOUDFLARE_TOKEN=YOUR_CLOUDFLARE_TOKEN" >> .env
echo "REBCA_FLUTTER_UPLOAD_URL=YOUR_UPLOAD_URL" >> .env
echo "REBCA_FLUTTER_UPLOAD_USERNAME=YOUR_UPLOAD_USERNAME" >> .env
echo "REBCA_FLUTTER_UPLOAD_PASSWORD=YOUR_UPLOAD_PASSWORD" >> .env
