name: game
description: Construção Criativa da Rebeca - jogo voxel modo criativo

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.16.0"

dependencies:
  dio_mock: ^1.0.0
  openapi: ^1.0.0
  permission_handler: ^11.0.0
  json_annotation: ^4.8.1
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  flutter_dotenv: ^5.0.2
  quiver: ^3.2.1
  freezed_annotation: ^2.4.1
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  mockito: ^5.4.4
  http: ^0.13.6
  http_mock_adapter: ^1.0.0
  ffmpeg_kit_flutter: ^4.5.1
  process_run: ^0.14.0+1

dev_dependencies:
  test_coverage: ^1.0.0
  test: ^1.24.3
  dio_mock: ^1.0.0
  openapi: ^1.0.0
  permission_handler: ^11.0.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  mockito: ^5.4.4
  flutter_dotenv: ^5.0.2
  quiver: ^3.2.1
  freezed: ^2.4.7
  build_runner: ^2.4.6
  freezed_annotation: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  dio: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/

  integration_test:
    path: test_driver/integration_test/integration_test.dart
  additional_test_paths:
    - test_driver/passdriver_flutter_version_check/version_check_test.dart

golden_toolkit: ^0.15.0

  additional_test_paths:
    - test_driver/passdriver_flutter_load_test/load_test.dart

  additional_test_paths:
    - test_driver/passdriver_flutter_permission_test/permission_test.dart

  additional_test_paths:
    - test_driver/passdriver_flutter_qos_test/qos_test.dart
