[env.production]
name = "construcao-criativa-production"

[env.staging]
name = "construcao-criativa-staging"

[site]
bucket = "./app/build/web"

[env.production.vars]
CF_PAGES_BRANCH = "main"

[env.staging.vars]
CF_PAGES_BRANCH = "staging"
