name = "passdriver-backend"
main = "./src/index.ts"
compatibility_date = "2023-12-01"

[env.production]
DB = "passdriver-db-production"
KV = "passdriver-kv-production"

[env.staging]
DB = "passdriver-db-staging"
KV = "passdriver-kv-staging"

[[env.production.kv_namespaces]]
binding = "KV"
id = "${passdriver-kv-production}"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "${passdriver-kv-staging}"

[[d1_databases]]
binding = "DB"
database_name = "passdriver-db"
database_id = "${passdriver-db-id}"
