name: Validação de Fetch de Dependências

on:
  push:
    branches:
      - main

jobs:
  validate-pub-get:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Run 'flutter pub get'
        run: flutter pub get

      - name: Check for errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Erro ao executar 'flutter pub get'"
            exit 1
          fi
