// Mocks generated by Mockito 5.4.4 from annotations
// in game/test/services/permission/permission_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i2;

class _FakePermissionStatus_0 extends _i1.SmartDartMockValue<_i2.PermissionStatus> {
  _FakePermissionStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Permission].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermission extends _i1.Mock implements _i2.Permission {
  MockPermission() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PermissionStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _FakePermissionStatus_0(
          this,
          Invocation.getter(#status),
        ),
      ) as _i2.PermissionStatus);

  @override
  _i2.Future<_i2.PermissionStatus> request() => (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
        ),
        returnValue: _i2.Future<_i2.PermissionStatus>.value(_FakePermissionStatus_0(
          this,
          Invocation.method(
            #request,
            [],
          ),
        )),
      ) as _i2.Future<_i2.PermissionStatus>);
}
