name: AGP Version Test

on:
  push:
    branches:
      - main

jobs:
  validate-agp-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate AGP version
        run: |
          AGP_VERSION=$(grep 'com.android.tools.build:gradle' android/build.gradle | awk '{print $NF}' | tr -d "'")
          echo "AGP Version: $AGP_VERSION"
          if [ "$(printf '%s\n' '7.4.2' "$AGP_VERSION" | sort -V | head -n1)" = '7.4.2' ]; then
            echo "AGP version is compatible with JDK 17"
          else
            echo "AGP version is not compatible with JDK 17"
            exit 1
          fi
