name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate deployment
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://rebcm.pages.dev | grep -q "200"
          if [ $? -ne 0 ]; then
            echo "Health check failed"
            exit 1
          fi
