name: Preview URL Validation

on:
  workflow_dispatch:

jobs:
  validate-preview-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Save Preview URL to File
        run: |
          echo "${{ steps.deploy.outputs.preview_url }}" > preview_url.txt
