    name: Validate Secrets
    
name: Define FPS KPI

on:
  workflow_dispatch:
    inputs:
      min_fps:
        description: 'Minimum FPS'
        required: true
        default: '55'
      max_jank_frames:
        description: 'Maximum Jank Frames'
        required: true
        default: '5'

      validate-secrets:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Validate Secrets
            run: .github/scripts/validate_secrets.sh
        continue-on-error: false
jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  define_kpi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define FPS KPI
        run: |
          echo "FPS_KPI=${{ github.event.inputs.min_fps }}" >> $GITHUB_ENV
          echo "JANK_FRAMES_KPI=${{ github.event.inputs.max_jank_frames }}" >> $GITHUB_ENV

      - name: Save KPI to file
        run: |
          mkdir -p performance_kpi
          echo "FPS_KPI=$FPS_KPI" > performance_kpi/fps_kpi.txt
          echo "JANK_FRAMES_KPI=$JANK_FRAMES_KPI" > performance_kpi/jank_frames_kpi.txt

      - name: Upload KPI file
        uses: actions/upload-artifact@v3
        with:
          name: performance_kpi
          path: performance_kpi/
