name: Input Stress Test

on:
  push:
    branches:
      - main

jobs:
  input-stress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run input stress test
        run: |
          flutter drive --target=test/integration_test/input_stress_test/input_stress_test.dart --driver=test_driver/integration_test.dart --profile
