name: Flutter e Dart Version Matrix Test

on:
  push:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter: ['3.0.0', '3.3.10']
        dart: ['2.17.0', '2.19.6']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter and Dart
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}
          channel: 'stable'
      - name: Check Flutter version
        run: flutter --version
      - name: Check Dart version
        run: dart --version
      - name: Run flutter pub get
        run: flutter pub get
      - name: Analyze code
        run: dart analyze
