name: Flutter e Dart Version Check

on:
  push:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verificar versão do Flutter e Dart
        run: |
          echo "Verificando versões do Flutter e Dart..."
          flutter --version
          dart --version

      - name: Executar teste de versão
        run: |
          dart test/flutter_dart_version_test.dart
