name: Flutter e Java Version Check

on:
  push:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Validate Flutter and Java versions
        run: |
          flutter --version > flutter_version.txt
          java -version > java_version.txt 2>&1
          dart test/flutter_dart_version_test.dart
