openapi: 3.0.0
info:
  title: Game API
  version: 1.0.0
paths:
  /data:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
