#!/bin/bash
flutter drive --driver=test/integration_tests/device_compatibility_test/device_compatibility_test_driver.dart --target=test/integration_tests/device_compatibility_test/device_compatibility_test.dart
