#!/bin/bash
flutter drive --driver=test/integration_tests/setup_validation_test_driver/setup_validation_test_driver.dart --target=test/integration_tests/setup_validation_test/setup_validation_test.dart
