#!/bin/bash
flutter drive --driver=test/integration_tests/uv_mapping_validation_test/uv_mapping_validation_test_driver.dart --target=test/integration_tests/uv_mapping_validation_test/uv_mapping_validation_test.dart
