#!/bin/bash
flutter drive --driver=test/integration_tests/acceptance_criteria_test/acceptance_criteria_test_driver.dart --target=test/integration_tests/acceptance_criteria_test/acceptance_criteria_test.dart
