import { Hono } from 'hono'; 
import { cors } from './middlewares/cors';
// existing imports...
const app = new Hono();
// existing middlewares...
app.use('*', cors);
// existing routes...
export default app;
