@startuml
participant App Flutter as "App Flutter"
participant Cloudflare Worker as "Cloudflare Worker"
participant Serviço de Armazenamento as "Serviço de Armazenamento"

App Flutter ->> Cloudflare Worker: Requisição de armazenamento
Cloudflare Worker ->> Serviço de Armazenamento: Requisição de armazenamento
Serviço de Armazenamento ->> Cloudflare Worker: Resposta de armazenamento
Cloudflare Worker ->> App Flutter: Resposta de armazenamento

@enduml
