name: Validacao Visual da Skin

on:
  pull_request:
    paths:
      - 'assets/blocos/**'

jobs:
  validate-skin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validacao da Skin
        run: |
          echo "Validando dimensoes da skin..."
          if [ $(identify -format "%wx%h" assets/blocos/skin.png) != "64x64" ]; then
            echo "Dimensoes incorretas"
            exit 1
          fi
          echo "Validacao concluida com sucesso"
