name: Check Secrets

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Secrets
        env:
          SECRET1: ${{ secrets.SECRET1 }}
          SECRET2: ${{ secrets.SECRET2 }}
        run: |
          if [ -z "$SECRET1" ] || [ -z "$SECRET2" ]; then
            echo "Secrets are not configured properly"
            exit 1
          fi
