// This file is generated by Mockito. Do not edit manually.
// To regenerate, run: flutter pub run build_runner build

import 'package:audioplayers/audioplayers.dart';
import 'package:mockito/mockito.dart';

class MockAudioPlayer extends Mock implements AudioPlayer {
  @override
  Future<String> play(AssetSource source, {double? volume, double? pitch}) {
    return super.noSuchMethod(Invocation.method(#play, [source], {#volume: volume, #pitch: pitch}), returnValue: Future.value('1')) as Future<String>;
  }

  @override
  Future<String> pause() {
    return super.noSuchMethod(Invocation.method(#pause, []), returnValue: Future.value('1')) as Future<String>;
  }

  @override
  Future<String> setVolume(double volume) {
    return super.noSuchMethod(Invocation.method(#setVolume, [volume]), returnValue: Future.value('1')) as Future<String>;
  }
}
