name: Audio Integration Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - name: Check Flutter version
        run: flutter --version
        with:
          flutter-version: '3.0.1'

      - name: Run integration test
        run: |
          flutter config --enable-web
          flutter drive --driver=test/integration_tests/audio_integration_test.dart --target=integration_test/main.dart
