name: Build iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: ./.github/scripts/build_ipa.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: game.ipa
          path: build/ios/ipa/game.ipa
