name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Secrets
        uses: ./.github/scripts/validate_secrets.sh

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build
