name: Build Daily

on:
  schedule:
    - cron: '0 23 * * *' # 20:00 BRT is 23:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: dart analyze

      - name: Build Flutter
        run: flutter build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
