name: build-ios

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Build IPA
        run: .github/scripts/build_ios.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rebcm.ipa
          path: build/ios/ipa/rebcm.ipa
