name: Build Web
on:
  push:
    branches:
      - main
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build and deploy
        run: |
          flutter config --enable-web
          flutter build web
          ls -l build/web
