name: Checklist Aceitação Arquitetura Test

on:
  pull_request:
    branches:
      - main

jobs:
  validate_checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate Checklist Aceitação Arquitetura
        run: ./.github/scripts/docs_validation/checklist_aceitacao_arquitetura/validate_checklist_aceitacao_arquitetura.sh
