name: Chunk Size Limit Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'

      - name: Run test
        run: |
          flutter drive --target=test_driver/integration_test/chunk_size_limit_test_config.dart --driver=test_driver/integration_test/chunk_size_limit_test.dart
