name: Chunking Heterogeneous Stress Test

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Check Flutter version
        run: flutter --version
        with:
          flutter-version: '3.0.1'

      - name: Run stress test
        run: |
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/stress_tests/chunking_heterogeneous_stress_test.dart
