name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          flutter test

      - name: Check Secrets Configuration
        uses: ./.github/workflows/secrets_validation/check_secrets.yml

      - name: Build and Deploy
        run: |
          flutter build web
          # deploy commands here
