name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Secrets
        uses: ./.github/workflows/configure-secrets.yml@main

      - name: Run Flutter Tests
        run: |
          flutter test
