name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger deploy web via Cloudflare
        uses: ./.github/workflows/deploy_automation/deploy_web_via_cloudflare.yml
