name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run upload edge cases test
        run: .github/scripts/ci_validation/upload_edge_cases_test/run_upload_edge_cases_test.sh
