name: CI

on:
  push:
    branches:
      - main

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate secrets
        run: .github/scripts/ci_validation/secrets_validation/validate_secrets.sh
