name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**
    tags:
      - '*'
  merge_request:
    types: [opened, updated]
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: dart analyze

      - name: Run tests
        run: flutter test

