name: Cleanup

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Purge artifacts
        run: .github/workflows/scripts/purge-artifacts.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
