name: Cloudflare Token Permissions Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  test-token-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Cloudflare Token Permissions
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          curl -X GET \
          "https://api.cloudflare.com/client/v4/user/tokens/verify" \
          -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
          -H "Content-Type: application/json" | jq '.result.permissions'
          curl -X GET \
          "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/settings" \
          -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
          -H "Content-Type: application/json" | jq '.result[] | select(.id == "dns")'
          curl -X GET \
          "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/settings" \
          -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
          -H "Content-Type: application/json" | jq '.result[] | select(.id == "security_header")'
