name: Compression Test

on:
  workflow_dispatch:

jobs:
  compression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run compression test
        run: |
          ./.github/workflows/scripts/validate_binary_version.sh
          ./scripts/define_compression_kpi.sh

      - name: Compare APK size with KPI
        run: |
          # Add logic to compare the APK size with the target size defined in the KPI report
          echo "Comparing APK size with KPI"
