name: Configure Secrets

on:
  workflow_dispatch:

jobs:
  configure-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Secrets
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          IOS_CERTIFICATE: ${{ secrets.IOS_CERTIFICATE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
        run: |
          echo "$ANDROID_KEYSTORE" | base64 --decode > android.keystore.jks
          echo "$IOS_CERTIFICATE" | base64 --decode > ios.certificate.p12
