name: Configure Secrets

on:
  workflow_dispatch:

jobs:
  configure-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decrypt secrets
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
        run: .github/scripts/secrets_management/decrypt_secrets.sh
