name: Configuracoes Test

on:
  push:
    branches:
      - main

jobs:
  test-configuracoes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Run configuracoes test
        run: |
          flutter test test/configuracoes_test/configuracoes_test.dart
