name: Coverage Pipeline

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: |
          flutter test --coverage

      - name: Check coverage threshold
        run: |
          coverage_threshold=$(cat .github/docs/code_coverage_criteria/criterios_aceitacao.md | grep -oP '(?<=threshold: )\d+')
          lcov --summary coverage/lcov.info
          coverage_percentage=$(lcov --summary coverage/lcov.info | grep -oP '(?<=lines\.\.\.\s)\d+(?:\.\d+)?%')
          echo "Coverage percentage: $coverage_percentage"
          if (( $(echo "$coverage_percentage < $coverage_threshold" | bc -l) )); then
            echo "Coverage percentage is less than the threshold ($coverage_threshold%)"
            exit 1
          fi
