name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Ambiente de deploy
        options:
          - staging
          - production

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Worker
        run: |
          wrangler deploy --env=${{ github.event.inputs.environment }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
