name: Deploy Test

on:
  push:
    branches:
      - main

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Validate Preview URL Script
        env:
          PREVIEW_URL: ${{ secrets.PREVIEW_URL }}
        run: ./scripts/validate_preview_url.sh $PREVIEW_URL
