name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'

      - name: Install dependencies
        run: flutter pub get

      - name: Validate environment config
        run: .github/scripts/ci_validation/env_config/validate_env_config.sh

      - name: Deploy
        run: .github/scripts/deploy.sh
