name: Docs Validation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Guia de Estilo Dicas
        run: .github/scripts/docs_validation/validate_guia_estilo_dicas.sh

