name: Docs Validation

on:
  push:
    branches:
      - main

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate documentation
        run: ./.github/scripts/docs_validation/checklist_validacao_documentacao/validate_checklist_documentacao.sh
