    name: Validate Secrets
    
name: Documentação Matriz de Erro

on:
  workflow_dispatch:

      validate-secrets:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Validate Secrets
            run: .github/scripts/validate_secrets.sh
        continue-on-error: false
jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  documentacao-matriz-erro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define matriz de erro
        run: ./.github/workflows/scripts/define_error_matrix.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: matriz_erro.txt
          path: ./documentacao/matriz_erro.txt
