name: Testar Diagrama de Sequência

on:
  push:
    branches:
      - main
    paths:
      - 'docs/diagramas/sequencia/**'

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Instalar PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      - name: Validar Diagrama
        run: |
          plantuml docs/diagramas/sequencia/flutter-cloudflare-autenticacao-comunicacao.puml -o docs/diagramas/sequencia/output
          if [ ! -f docs/diagramas/sequencia/output/flutter-cloudflare-autenticacao-comunicacao.png ]; then
            echo "Falha ao gerar diagrama"
            exit 1
          fi
