name: Testar Diagrama de Sequência de Integração

on:
  push:
    branches:
      - main
    paths:
      - 'docs/diagramas/sequencia/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validar Diagrama
        run: |
          sudo apt-get install -y plantuml
          plantuml docs/diagramas/sequencia/integracao-flutter-cloudflare.puml -o docs/diagramas/sequencia/output
