name: Testar Documentação Matriz Velocidade Frame Rate

on:
  push:
    branches:
      - main
    paths:
      - 'assets/docs/matriz_velocidade_frame_rate.md'

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verificar arquivo
        run: |
          test -f assets/docs/matriz_velocidade_frame_rate.md
