name: Documentação Revisão

on:
  pull_request:
    paths:
      - '.github/docs/**'

jobs:
  documentacao-revisao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verificar checklist de documentação
        run: |
          if ! grep -q "Checklist de Documentação" .github/docs/documentacao_revisao_fluxo/fluxo_revisao.md; then
            echo "Documentação não atende ao checklist"
            exit 1
          fi
