name: Edge Cases Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run edge cases tests
        run: |
          flutter test test/widget_test/edge_cases
      - name: Run integration edge cases tests
        run: |
          flutter drive --driver=test/integration_test/edge_cases/integration_test.dart --target=test/integration_test/edge_cases/integration_test.dart
