name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode keystores
        env:
          KEYSTORE_JKS_BASE64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
          KEYSTORE_P12_BASE64: ${{ secrets.KEYSTORE_P12_BASE64 }}
        run: .github/workflows/scripts/decode_keystores.sh

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter
        run: flutter build apk --release
