name: Flutter Pipeline

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test

      - name: Build Flutter app
        run: flutter build apk --release
