name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'

      - name: Build and validate artifact
        run: |
          flutter build web
          .github/workflows/scripts/validate_build_artifact.sh "build/web/index.html"
