name: Flutter Doctor

on:
  push:
    branches:
      - main

jobs:
  flutter-doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run flutter doctor
        run: ./.github/scripts/ci_validation/flutter_doctor/run_flutter_doctor.sh
