name: Flutter Environment Integration Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - name: Run integration test
        run: |
          flutter pub get
          flutter test test/integration/flutter_environment/flutter_environment_test.dart
