name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decrypt secrets
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
        run: .github/scripts/secrets_management/decrypt_secrets.sh

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter
        run: flutter build apk --release
