name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode keystores
        env:
          KEYSTORE_JKS_BASE64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
          KEYSTORE_P12_BASE64: ${{ secrets.KEYSTORE_P12_BASE64 }}
        run: .github/scripts/passdriver/decode_keystores.sh

      - name: Build Flutter
        run: |
          flutter pub get
          flutter build apk
          flutter build ios --no-codesign
