name: Flutter Pipeline

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Run flutter pub get
        run: flutter pub get

      - name: Run flutter test
        run: flutter test

      - name: Run flutter driver test
        run: flutter drive --target=test_driver/app.dart
