name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decrypt keystore
        env:
          KEYSTORE_ENCRYPTED: ${{ secrets.KEYSTORE_ENCRYPTED }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: .github/scripts/secrets_management/decrypt_keystore.sh

      - name: Build Flutter app
        run: |
          flutter pub get
          flutter build apk --release
