name: Validate Gradle JDK 17 Compatibility

on:
  push:
    branches:
      - main

jobs:
  validate-gradle-jdk17:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Gradle JDK 17 Compatibility
        run: ./.github/scripts/docs_validation/validate_gradle_jdk17_compatibilidade.sh
