name: Input Stress Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run input stress test
        run: |
          flutter drive --target=test/integration_tests/input_stress_test/input_stress_test.dart
