name: Input Stress Test

on:
  schedule:
    - cron:  '0 12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test integration_test/input/input_stress_test.dart
