name: Integracao API Staging Test

on:
  push:
    branches:
      - main

jobs:
  integracao-api-staging-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Run integration test
        run: |
          flutter drive --target=integration_test/api_staging_test/rebeca_api_staging_test.dart --driver=test_driver/integration_test.dart
