name: Integração com Limpeza

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run integration tests with cleanup
        run: |
          flutter drive --target=integration_test/app_test.dart --driver=integration_test/driver.dart
          .github/workflows/scripts/cleanup.sh

      - name: Cleanup after tests
        env:
          CLEANUP_SCRIPT: .github/workflows/scripts/cleanup.sh
        run: |
          $CLEANUP_SCRIPT
