name: Integration Test with Mock

on:
  push:
    branches:
      - main

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run integration tests with mock
        run: flutter test integration_test/artefato_test.dart
