name: Integracao API Test

on:
  push:
    branches:
      - main

jobs:
  integracao-api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run API integration tests
        run: |
          flutter test test/integration/api/api_test.dart
