name: Integration Test with Mock

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - name: Run integration test with mock
        run: flutter test integration_test/passdriver_integration_test.dart
