name: Integracao API Test

on:
  push:
    branches:
      - main

jobs:
  integracao-api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'

      - name: Run integration tests
        run: |
          flutter drive --driver=test/integration/api/api_test.dart --target=lib/main.dart
