name: API Integration Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run API integration test
        run: |
          flutter pub get
          flutter test test/integration/api/api_test.dart
