    name: Validate Secrets
    
name: Integracao Test

on:
  push:
    branches:
      - main

      validate-secrets:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Validate Secrets
            run: .github/scripts/validate_secrets.sh
        continue-on-error: false
jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  integracao-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Run integration tests
        run: flutter test test/integracao/api_test.dart
