name: Integration Test HTTP Errors

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - name: Check Flutter version
        run: flutter --version
        with:
          flutter-version: '3.0.1'

      - name: Run integration tests
        run: |
          flutter drive --target=test/integration_tests/http_error_test.dart --driver=test_driver/integration_test.dart
