name: Integration Tests

on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Run integration tests
        run: |
          flutter drive --target=test/integration_tests/scroll_bloqueio_test.dart --driver=test/integration_tests/integration_test_driver.dart --browser=chrome
          flutter drive --target=test/integration_tests/scroll_bloqueio_test.dart --driver=test/integration_tests/integration_test_driver.dart --browser=firefox
          flutter drive --target=test/integration_tests/scroll_bloqueio_test.dart --driver=test/integration_tests/integration_test_driver.dart --browser=safari
