    name: Validate Secrets
    
name: Integração Rede Test

on:
  push:
    branches:
      - main

      validate-secrets:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Validate Secrets
            run: .github/scripts/validate_secrets.sh
        continue-on-error: false
jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Check Flutter version
        run: flutter --version
        with:
          flutter-version: '3.0.5'
      - run: flutter pub get
      - run: flutter test test/integracao/rede/tempo_limite_rede_test.dart
