name: Reexecução de Testes de Integração

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  reexecuta-testes-integracao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Run integration tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
