name: Jank Test

on:
  push:
    branches:
      - main

jobs:
  jank-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run jank test
        run: |
          flutter test lib/test/performance/jank_test.dart
