name: Lint Error Test

on:
  push:
    branches:
      - main

jobs:
  lint-error-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Run Lint Error Test
        run: |
          flutter drive --driver=test/integration_tests/lint_error_test/lint_error_test_driver.dart --target=test/integration_tests/lint_error_test/lint_error_test.dart
