name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Build APK
        run: flutter build apk --release

      - name: Build IPA
        run: flutter build ipa --release

      - name: Upload artifacts
        run: .github/workflows/scripts/upload-artifact.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
