name: Markdown Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Lint Markdown
        run: |
          bash ./.github/scripts/markdown_lint/lint_markdown.sh
