name: Memory Consumption Test

on:
  push:
    branches:
      - main

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  memory-consumption-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Run memory consumption test
        run: |
          flutter drive --target=test/performance_tests/memory_consumption_test.dart --driver=test_driver/integration_test.dart --profile
