name: Onboarding Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      - run: flutter config --enable-integration-testing
      - run: flutter drive --driver=test_driver/onboarding_test/onboarding_test_driver.dart --target=test_driver/onboarding_test/onboarding_test.dart
