name: OpenAPI Contract Test

on:
  push:
    paths:
      - 'docs/api/openapi.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate OpenAPI contract
        run: ./.github/scripts/docs_validation/validate_openapi_contract_test.sh
