name: Passdriver Flutter Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download KPI file
        uses: actions/download-artifact@v3
        with:
          name: performance_kpi
          path: performance_kpi/

      - name: Run Flutter performance test
        run: ./passdriver_flutter_test.sh
