name: PassDriver API Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PassDriver API tests
        run: |
          flutter test test/passdriver_api_test
