name: Performance e Memória Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Run performance and memory tests
        run: flutter drive --target=test_driver/app.dart --driver=test_driver/performance_test.dart
