name: Persistência após Flutter Clean Test

on:
  push:
    branches:
      - main

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
      - name: Check Java version
        run: java -version
        with:
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Check Flutter version
        run: flutter --version
        with:
          flutter-version: '3.0.5'

      - name: Flutter Clean
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build and test
        run: flutter run --release
