name: Persistência Crash Test

on:
  push:
    branches:
      - main

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Check Flutter version
        run: flutter --version
        with:
          flutter-version: '3.0.1'

      - name: Run integration test
        run: |
          flutter drive --target=integration_test/persistencia_test/simulacao_crash_app_test.dart --driver=test_driver/integration_test.dart --profile
