name: Purge Test

on:
  workflow_dispatch:

jobs:
  purge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Purge Script
        run: |
          .github/workflows/scripts/purge-artifacts.sh
