    name: Validate Secrets
    
name: Purge Test

on:
  workflow_dispatch:

      validate-secrets:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Validate Secrets
            run: .github/scripts/validate_secrets.sh
        continue-on-error: false
jobs:
  purge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Purge Script
        run: |
          .github/workflows/scripts/purge-artifacts.sh
