name: README Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - README.md

jobs:
  validate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate README.md
        run: .github/docs/readme_validation/validation_script.sh
