name: Release

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Cloudflare Secrets
        uses: ./.github/workflows/validate-cloudflare-secrets.yml
