name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update version
        run: ./.github/workflows/scripts/update_version.sh

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build and release
        run: |
          # Existing build and release commands here
