name: Responsividade Test

on:
  push:
    branches:
      - main

jobs:
  responsividade-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Run responsividade tests
        run: |
          flutter test test/responsividade/tela_pequena_test.dart
