name: Validate Secrets

on:
  push:
    branches:
      - main

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate secrets
        run: ./.github/scripts/secrets_validation/validate_secrets.sh
        env:
          KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
