name: Sincronizar Documentação

on:
  pull_request:
    branches:
      - main
    paths:
      - .env
      - pubspec.yaml

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Executar script de sincronização
        run: .github/scripts/sync_docs.sh

      - name: Commit alterações
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Sincroniza documentação" || echo "Nenhuma alteração para commitar"
