name: Testes de API

on:
  push:
    branches:
      - main

jobs:
  testes-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Run API tests
        run: flutter test test/api_test/api_test.dart
