name: Testes de Integração da API

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test lib/test/integracao/api/test_api.dart
