name: Upload Stress Test

on:
  push:
    branches:
      - main

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  upload_stress_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - name: Check Flutter version
        run: flutter --version
        with:
          flutter-version: '3.0.1'

      - name: Run upload stress test
        run: |
          flutter pub get
          flutter drive --target=test/integration_tests/upload_stress_test/upload_stress_test.dart --driver=test_driver/integration_test.dart
