name: Upload Stress Test

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter pub get
      - run: flutter test integration_test/sincronizacao/upload_stress_test.dart
