name: Validate Installation Documentation

on:
  push:
    branches:
      - main

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Validate installation documentation
        run: ./.github/docs/installation_docs_validation/validate_installation_docs.sh
