name: Validate Glossario

on:
  push:
    branches:
      - main

jobs:
  validate_glossario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run extract glossario script
        run: ./.github/scripts/docs_validation/glossario/run_extract_glossario.sh

      - name: Validate glossario
        run: ./.github/scripts/docs_validation/glossario/validate_glossario.sh
