name: Validate Secrets

on:
  push:
    branches:
      - main

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.KEYSTORE }}" ]; then
            echo "KEYSTORE secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_PASSWORD }}" ]; then
            echo "KEYSTORE_PASSWORD secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEY_ALIAS }}" ]; then
            echo "KEY_ALIAS secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEY_PASSWORD }}" ]; then
            echo "KEY_PASSWORD secret is not set"
            exit 1
          fi
