name: Validate Cloudflare Token

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  validate-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load .env file
        run: |
          source .env

      - name: Validate Cloudflare Token
        run: ./scripts/validate_cloudflare_token.sh

