name: Validate Checklist Build

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate checklist build
        run: ./.github/scripts/ci_validation/checklist_build_validation/validate_checklist_build.sh
