name: Validate Checksum

on:
  push:
    branches:
      - main

jobs:
  validate-checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'

      - name: Run checksum test
        run: bash scripts/run_checksum_test.sh
