name: Validate Artifact Signature

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Plataforma (android, ios, checksum)'
        required: true
      file_path:
        description: 'Caminho do arquivo'
        required: true
      expected_checksum:
        description: 'Checksum esperado (para validação via checksum)'
        required: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate signature
        run: |
          .github/workflows/scripts/validate_signature.sh ${{ inputs.platform }} ${{ inputs.file_path }} ${{ inputs.expected_checksum }}
