name: Validate Artifact

on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
      artifact:
        required: true
      checksum:
        required: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate artifact
        run: |
          .github/workflows/scripts/validate_signature.sh ${{ inputs.platform }} ${{ inputs.artifact }} ${{ inputs.checksum }}
